
[stats]

	#Server configuration settings
	[stats.steady_guard]
		#Max Level Limit for this stat, -1 for leave it as-is, 0 for disable this stat.
		#Range: > -1
		maxLevel = -1
		#Cost multiplier for this stat
		#Range: 0.0 ~ 1.7976931348623157E308
		costMultiplier = 1.0
		#Bonus multiplier for this stat
		#Range: 0.0 ~ 1.7976931348623157E308
		bonusMultiplier = 1.0

